project:
  type: website
  output-dir: docs  # Important: This makes GitHub hosting easier later

website:
  title: Dario Bocchi  # Will appear in the top left corner
  favicon: images/perceptron.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: papers.qmd
        text: Papers
      - href: presentations.qmd
        text: Presentations
    right:
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?user=LQc7rbIAAAAJ
        aria-label: Google Scholar
      - icon: github
        href: https://github.com/dr-bocchi
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/dario-bocchi-025999218/
        aria-label: LinkedIn


format:
  html:
    theme: cosmo  # Try others later: darkly, flatly, journal, litera
    css: styles.css
    toc: true
    include-after-body: life.html